name: BuildAndPushDockerImage

on:
  push:
    branches: [ master ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v2

      - name: Login into docker hub
        run: docker login -u ${{secrets.DOCKER_HUB_USER}} -p ${{secrets.DOCKER_HUB_PASS}}

      - name: Build and push into registry
        run: npm run docker
